### ISSUE TITLE
Make paths relative from `config.root`

### ISSUE THREAD

**Issue by brillout** [antfu/vite-plugin-glob#6]
If we merge https://github.com/antfu/vite-plugin-glob/pull/5 then I would propose this:

```js
// Pre-transform
import.meta.importGlob('/**/*.page.js')

// Post-transform today
{
  "../../../../../examples/vue/renderer/_default.page.client.js": () =>
    import("../../../../../examples/vue/renderer/_default.page.client.js")
}

// Post-transform proposal (`config.root` being `'/examples/vue/'`)
{
  "/renderer/_default.page.client.jsx": () =>
    import("../../../../../examples/vue/renderer/_default.page.client.jsx")
}
```

This is what Vite does today.

**Comment by antfu** [comment]
Is that when the glob is `/` the so as the object key, or has it always been relative to `/`? Or maybe it's worth making it configurable?

**Comment by brillout** [comment]
Yes Vite does that when the glob starts with `/`. (Less sure otherwise.)

Regardless of Vite, I'd say that a sensible default is to preserve the glob syntax:

```js
import.meta.importGlob('/**/*.js')
// Post-transform
{ "/path/to/some.js": () => import(/* ... */) }

import.meta.importGlob('./**/*.js')
// Post-transform
{ "./path/to/some.js": () => import(/* ... */) }

// We currently don't support that syntax, but in case we want to in the future:
import.meta.importGlob('**/*.js')
// Post-transform
{ "path/to/some.js": () => import(/* ... */) }
```

I'd say that this is what I would expect as a user.

Proposal: https://github.com/antfu/vite-plugin-glob/pull/7. It also includes a new option `filePathsRelativeToRoot`.

**Comment by brillout** [comment]
Implemented by https://github.com/antfu/vite-plugin-glob/pull/7.
